select
    p.*,
    millisecond(p.process_term - p.process_started) / 1000 duration_seconds,
    r.total_activity_types reg_totals,
    r.reads reg_reads,
    r.writes reg_writes,
    r.createkeys reg_createkeys,
    r.deletekeys reg_deletekeys,
    r.deletevalues reg_deletevalues,
    r.first_seen reg_first_seen,
    r.last_seen reg_last_seen,
    f.Close_Events,
    f.Create_Events,
    f.Delete_Events,
    f.Rename_Events,
    f.SetInfo_Events,
    f.Read_Bytes,
    f.Read_Events,
    f.Write_Bytes,
    f.Write_Events,
    f.num_raw_rows file_num_raw_rows,
    f.num_uniq_file_hash,
    f.num_null_filename,
    f.first_seen file_first_seen,
    f.last_seen file_last_seen,
    n.conn_id_count,
    n.net_total_events,
    n.net_total_size,
    n.num_raw_rows net_num_raw_rows,
    n.tcp_accept_count,
    n.tcp_connect_count,
    n.tcp_disconnect_count,
    n.tcp_reconnect_count,
    n.tcp_recv_count,
    n.tcp_recv_size,
    n.tcp_retransmit_count,
    n.tcp_send_count,
    n.tcp_send_size,
    n.tcp_tcpcopy_count,
    n.tcp_tcpcopy_size,
    n.udp_recv_count,
    n.udp_recv_size,
    n.udp_send_count,
    n.udp_send_size,
    n.net_recv_size,
    n.net_send_size,
    n.net_rs_total,
    n.net_send_vs_recv,
    n.tcp_rs_total,
    n.tcp_send_vs_recv,
    n.udp_rs_total,
    n.udp_send_vs_recv,
    n.min_bytes,
    n.max_bytes,
    n.avg_bytes,
    n.min_packets,
    n.max_packets,
    n.avg_packets,
    n.sq_size,
    n.first_seen net_first_seen,
    n.last_seen net_last_seen,
    i.dlls,
    i.num_uniq_files dll_num_uniq_files,
    i.first_seen dll_first_seen,
    i.last_seen dll_last_seen,
    h.os,
    h.os_version,
    h.arch
from {{ ref('process') }} p
join {{ ref('host') }} h on h.hostname = p.hostname
left outer join {{ ref('process_registry_summary') }} r on p.pid_hash = r.pid_hash
left outer join {{ ref('process_net_summary') }} n on p.pid_hash = n.pid_hash
left outer join {{ ref('process_file_summary') }} f on p.pid_hash = f.pid_hash
left outer join {{ ref('process_image_load_summary') }} i on p.pid_hash = i.pid_hash
