{% if pidstat_data_exists() %}
select
    cast(concat(date_col, ' ', "Time") as timestamp) as time,
    cast("UID" as integer) as uid,
    cast("PID" as integer) as pid,
    cast("%usr" as {{ real_type() }}) as usr_percent,
    cast("%system" as {{ real_type() }}) as system_percent,
    cast("%guest" as {{ real_type() }}) as guest_percent,
    cast("%wait" as {{ real_type() }}) as wait_percent,
    cast("%CPU" as {{ real_type() }}) as cpu_percent,
    cast("CPU" as integer) as cpu_core,
    cast("minflt/s" as {{ real_type() }}) as minflt_per_sec,
    cast("majflt/s" as {{ real_type() }}) as majflt_per_sec,
    cast("VSZ" as bigint) as vsz_kb,
    cast("RSS" as bigint) as rss_kb,
    cast("%MEM" as {{ real_type() }}) as mem_percent,
    cast("kB_rd/s" as {{ real_type() }}) as kb_read_per_sec,
    cast("kB_wr/s" as {{ real_type() }}) as kb_write_per_sec,
    cast("kB_ccwr/s" as {{ real_type() }}) as kb_cancelled_write_per_sec,
    cast(iodelay as integer) as iodelay_ticks,
    cast("cswch/s" as {{ real_type() }}) as context_switch_per_sec,
    cast("nvcswch/s" as {{ real_type() }}) as nonvoluntary_context_switch_per_sec,
    command,
    filename
from {{ csv_relation(pidstat_csv_glob()) }}
{% else %}
select
    cast(null as timestamp) as time,
    cast(null as integer) as uid,
    cast(null as integer) as pid,
    cast(null as {{ real_type() }}) as usr_percent,
    cast(null as {{ real_type() }}) as system_percent,
    cast(null as {{ real_type() }}) as guest_percent,
    cast(null as {{ real_type() }}) as wait_percent,
    cast(null as {{ real_type() }}) as cpu_percent,
    cast(null as integer) as cpu_core,
    cast(null as {{ real_type() }}) as minflt_per_sec,
    cast(null as {{ real_type() }}) as majflt_per_sec,
    cast(null as bigint) as vsz_kb,
    cast(null as bigint) as rss_kb,
    cast(null as {{ real_type() }}) as mem_percent,
    cast(null as {{ real_type() }}) as kb_read_per_sec,
    cast(null as {{ real_type() }}) as kb_write_per_sec,
    cast(null as {{ real_type() }}) as kb_cancelled_write_per_sec,
    cast(null as integer) as iodelay_ticks,
    cast(null as {{ real_type() }}) as context_switch_per_sec,
    cast(null as {{ real_type() }}) as nonvoluntary_context_switch_per_sec,
    cast(null as varchar) as command,
    cast(null as varchar) as filename
where false
{% endif %}
