{% if pidstat_data_exists() %}
select
    time,
    uid,
    pid,
    usr_percent,
    system_percent,
    guest_percent,
    wait_percent,
    cpu_percent,
    cpu_core,
    minflt_per_sec,
    majflt_per_sec,
    vsz_kb,
    rss_kb,
    mem_percent,
    kb_read_per_sec,
    kb_write_per_sec,
    kb_cancelled_write_per_sec,
    iodelay_ticks,
    context_switch_per_sec,
    nonvoluntary_context_switch_per_sec,
    command,
    hostname,
    cgroup_path,
    pid_ns_inode,
    container_runtime,
    container_id,
    filename
from read_parquet(
    '{{ pidstat_parquet_glob() }}',
    filename=true
)
{% else %}
select
    cast(null as timestamp) as time,
    cast(null as integer) as uid,
    cast(null as integer) as pid,
    cast(null as real) as usr_percent,
    cast(null as real) as system_percent,
    cast(null as real) as guest_percent,
    cast(null as real) as wait_percent,
    cast(null as real) as cpu_percent,
    cast(null as integer) as cpu_core,
    cast(null as real) as minflt_per_sec,
    cast(null as real) as majflt_per_sec,
    cast(null as bigint) as vsz_kb,
    cast(null as bigint) as rss_kb,
    cast(null as real) as mem_percent,
    cast(null as real) as kb_read_per_sec,
    cast(null as real) as kb_write_per_sec,
    cast(null as real) as kb_cancelled_write_per_sec,
    cast(null as integer) as iodelay_ticks,
    cast(null as real) as context_switch_per_sec,
    cast(null as real) as nonvoluntary_context_switch_per_sec,
    cast(null as varchar) as command,
    cast(null as varchar) as hostname,
    cast(null as varchar) as cgroup_path,
    cast(null as bigint) as pid_ns_inode,
    cast(null as varchar) as container_runtime,
    cast(null as varchar) as container_id,
    cast(null as varchar) as filename
where false
{% endif %}
