name: 'wintap_dbt'
version: '0.1.0'
config-version: 2

profile: 'wintap_dbt'

model-paths: ['models']
macro-paths: ['macros']
test-paths: ['tests']
seed-paths: ['seeds']
analysis-paths: ['analyses']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

vars:
  dataset: "{{ env_var('WINTAP_DBT_DATASET') }}"
  start_day: "{{ env_var('WINTAP_DBT_START_DAY') }}"
  end_day: "{{ env_var('WINTAP_DBT_END_DAY') }}"
  include_monitoring: "{{ env_var('WINTAP_DBT_INCLUDE_MONITORING', 'true') }}"

models:
  wintap_dbt:
    bronze:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
    monitoring:
      +materialized: view
      +enabled: "{{ env_var('WINTAP_DBT_INCLUDE_MONITORING', 'True') == 'True' }}"
