select
    hostname,
    {{ array_agg_distinct_sorted('agentid') }} agent_ids,
    any_value('windows') os_family,
    to_timestamp(min(cast(eventtime as bigint))) first_seen,
    to_timestamp(max(cast(eventtime as bigint))) last_seen,
    any_value(os) os,
    count(distinct os) num_os,
    any_value(case when osversion = '' then null else osversion end) os_version,
    count(distinct osversion) num_os_version,
    any_value(case when arch = '' then null else arch end) arch,
    count(distinct arch) num_arch,
    any_value(processorcount) processor_count,
    count(distinct processorcount) num_processor_count,
    any_value(processorspeed) processor_speed,
    count(distinct processorspeed) num_processor_speed,
    any_value(hasbattery) has_battery,
    count(distinct hasbattery) num_has_battery,
    any_value(domain) ad_domain,
    count(distinct domain) num_ad_domain,
    any_value(domainrole) domain_role,
    count(distinct domainrole) num_domain_role,
    max(lastboot) last_boot,
    count(distinct lastboot) num_last_boot,
    max(wintapversion) wintap_version,
    count(distinct wintapversion) num_wintap_version,
    max(etlversion) etl_version,
    count(distinct etlversion) num_etl_version,
    count(*) num_rows
from {{ ref('stg_raw_host') }}
group by all
