select
    'windows' os_family,
    agentid agent_id,
    hostname,
    pidhash pid_hash,
    processname process_name,
    connid conn_id,
    protocol protocol,
    {{ to_timestamp_micros_expr('floor(' ~ win32_to_epoch_expr('cast(firstseenms as bigint)') ~ ' / 60) * 60') }} incr_start,
    {{ int_to_ip_expr('cast(localipaddr as bigint)') }} local_ip_addr,
    localipaddr local_ip_int,
    localport local_port,
    {{ int_to_ip_expr('cast(remoteipaddr as bigint)') }} remote_ip_addr,
    remoteipaddr remote_ip_int,
    remoteport remote_port,
    sum(eventcount) total_events,
    sum(packetsize) total_size,
    count(*) num_raw_rows,
    sum(case when ipevent = 'TcpIp/Accept' then eventcount end) tcp_accept_count,
    sum(case when ipevent = 'TcpIp/Connect' then eventcount end) tcp_connect_count,
    sum(case when ipevent = 'TcpIp/Disconnect' then eventcount end) tcp_disconnect_count,
    sum(case when ipevent = 'TcpIp/Reconnect' then eventcount end) tcp_reconnect_count,
    sum(case when ipevent = 'TcpIp/Recv' then eventcount end) tcp_recv_count,
    sum(case when ipevent = 'TcpIp/Recv' then packetsize end) tcp_recv_size,
    sum(case when ipevent = 'TcpIp/Retransmit' then eventcount end) tcp_retransmit_count,
    sum(case when ipevent = 'TcpIp/Send' then eventcount end) tcp_send_count,
    sum(case when ipevent = 'TcpIp/Send' then packetsize end) tcp_send_size,
    sum(case when ipevent = 'TcpIp/TCPCopy' then eventcount end) tcp_tcpcopy_count,
    sum(case when ipevent = 'TcpIp/TCPCopy' then packetsize end) tcp_tcpcopy_size,
    sum(case when ipevent = 'UdpIp/Recv' then eventcount end) udp_recv_count,
    sum(case when ipevent = 'UdpIp/Recv' then packetsize end) udp_recv_size,
    sum(case when ipevent = 'UdpIp/Send' then eventcount end) udp_send_count,
    sum(case when ipevent = 'UdpIp/Send' then packetsize end) udp_send_size,
    min(eventcount) min_10sec_eventcount,
    max(eventcount) max_10sec_eventcount,
    min(minpacketsize) min_size,
    max(maxpacketsize) max_size,
    sum(packetsizesquared) sq_size,
    max(case when ipevent = 'TcpIp/Recv' then eventcount end) max_tcp_recv_count,
    min(case when ipevent = 'TcpIp/Recv' then minpacketsize end) min_tcp_recv_size,
    max(case when ipevent = 'TcpIp/Recv' then maxpacketsize end) max_tcp_recv_size,
    sum(case when ipevent = 'TcpIp/Recv' then packetsizesquared end) sq_tcp_recv_size,
    max(case when ipevent = 'TcpIp/Send' then eventcount end) max_tcp_send_count,
    min(case when ipevent = 'TcpIp/Send' then minpacketsize end) min_tcp_send_size,
    max(case when ipevent = 'TcpIp/Send' then maxpacketsize end) max_tcp_send_size,
    sum(case when ipevent = 'TcpIp/Send' then packetsizesquared end) sq_tcp_send_size,
    max(case when ipevent = 'UdpIp/Recv' then eventcount end) max_udp_recv_count,
    min(case when ipevent = 'UdpIp/Recv' then minpacketsize end) min_udp_recv_size,
    max(case when ipevent = 'UdpIp/Recv' then maxpacketsize end) max_udp_recv_size,
    sum(case when ipevent = 'UdpIp/Recv' then packetsizesquared end) sq_udp_recv_size,
    max(case when ipevent = 'UdpIp/Send' then eventcount end) max_udp_send_count,
    min(case when ipevent = 'UdpIp/Send' then minpacketsize end) min_udp_send_size,
    max(case when ipevent = 'UdpIp/Send' then maxpacketsize end) max_udp_send_size,
    sum(case when ipevent = 'UdpIp/Send' then packetsizesquared end) sq_udp_send_size,
    {{ win32_to_timestamp_expr('min(cast(firstseenms as bigint))') }} first_seen,
    {{ win32_to_timestamp_expr('max(cast(lastseenms as bigint))') }} last_seen
from {{ ref('stg_raw_process_conn_incr') }}
group by all
