select
    os_family,
    agent_id,
    hostname,
    pid_hash,
    any_value(os_pid) os_pid,
    process_name,
    conn_id,
    protocol,
    source_ip_address_string,
    destination_ip_address_string,
    local_ip_addr,
    local_ip_private_gateway,
    local_port,
    remote_ip_addr,
    remote_ip_private_gateway,
    remote_port,
    sum(total_events) total_events,
    sum(total_size) total_size,
    sum(sq_size) sq_size,
    sum(num_raw_rows) num_raw_rows,
    sum(tcp_accept_count) tcp_accept_count,
    sum(tcp_connect_count) tcp_connect_count,
    sum(tcp_disconnect_count) tcp_disconnect_count,
    sum(tcp_reconnect_count) tcp_reconnect_count,
    sum(tcp_recv_count) tcp_recv_count,
    sum(tcp_recv_size) tcp_recv_size,
    sum(sq_tcp_recv_size) sq_tcp_recv_size,
    sum(tcp_retransmit_count) tcp_retransmit_count,
    sum(tcp_send_count) tcp_send_count,
    sum(tcp_send_size) tcp_send_size,
    sum(sq_tcp_send_size) sq_tcp_send_size,
    sum(tcp_tcpcopy_count) tcp_tcpcopy_count,
    sum(tcp_tcpcopy_size) tcp_tcpcopy_size,
    sum(udp_recv_count) udp_recv_count,
    sum(udp_recv_size) udp_recv_size,
    sum(sq_udp_recv_size) sq_udp_recv_size,
    sum(udp_send_count) udp_send_count,
    sum(udp_send_size) udp_send_size,
    sum(sq_udp_send_size) sq_udp_send_size,
    min(first_seen) first_seen,
    max(last_seen) last_seen
from {{ ref('process_conn_incr') }}
group by all
